access_key          = ""
secret_key          = ""
region              = ""
key_name            = ""
ssh_key_path        = ""
instance-type       = "ecs.g7ne.xlarge"
linux_instance_type = "ecs.g5.large"
linux_password      = "PaloAlto123!"
bootstrap           = "no"
auth_code           = ""
panos_version       = "11.2.2"
disk_category       = "cloud_essd"
fw_zone = ["", ""]   // example --> fw_zone = ["cn-shanghai-b", "cn-shanghai-l"]
image_id = ""
